"""ID generation. docs/API_CONTRACT.md requires opaque UUID v4 strings for
every resource id, generated by the application before persistence."""

from __future__ import annotations

import uuid


def new_id() -> str:
    return str(uuid.uuid4())
