"""source_items and document_snapshots -- Phase-1 persistence foundation

Creates exactly the two tables docs/adr/0002-postgres-pgvector.md section
7 authorizes for the first persistence PR: `source_items` and
`document_snapshots`, their constraints, foreign keys, the
`/v1/updates` keyset index, and the Phase-1 immutability triggers
(section 11). Hand-written, not autogenerated -- autogenerate does not
reliably emit `text[]` columns or trigger DDL (section 16, "Autogenerate
blind spots"). Neither creates nor drops `alembic_version`; Alembic
creates and manages that table itself (section 7).

Authored by Person A (ingestion review steward) because this migration
creates ingestion-owned tables and their triggers (section 12.5).

Revision ID: 0001
Revises:
Create Date: 2026-09-04
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None

# -- Trigger/function names -- one place, reused by both upgrade() and
# downgrade() so the two can never name a different object by accident.
_SOURCE_ITEMS_IDENTITY_FUNCTION = "source_items_protect_identity"
_SOURCE_ITEMS_IDENTITY_TRIGGER = "source_items_protect_identity_trigger"
_SNAPSHOTS_BLOCK_UPDATE_FUNCTION = "document_snapshots_block_update"
_SNAPSHOTS_BLOCK_UPDATE_TRIGGER = "document_snapshots_block_update_trigger"
_SNAPSHOTS_BLOCK_DELETE_FUNCTION = "document_snapshots_block_delete"
_SNAPSHOTS_BLOCK_DELETE_TRIGGER = "document_snapshots_block_delete_trigger"
_SNAPSHOTS_BLOCK_TRUNCATE_FUNCTION = "document_snapshots_block_truncate"
_SNAPSHOTS_BLOCK_TRUNCATE_TRIGGER = "document_snapshots_block_truncate_trigger"

_LATEST_SNAPSHOT_FK_NAME = "fk_source_items_latest_snapshot_id_document_snapshots"
_KEYSET_INDEX_NAME = "ix_source_items_first_fetched_at_id"

# The five source_items columns that must never change after insertion
# (ADR 0002 section 11, layer 3). Listed once, so a future migration
# that adds a sixth protected column touches exactly this list, per the
# "Trigger maintenance" reviewer checklist item in the ADR's Risks
# section.
_PROTECTED_SOURCE_ITEM_COLUMNS: tuple[str, ...] = (
    "id",
    "first_fetched_at",
    "dedupe_key",
    "source_id",
    "canonical_url",
)


def upgrade() -> None:
    # -- 1. source_items, WITHOUT the latest_snapshot_id FK yet --------
    # ADR 0002 section 9's circular-FK resolution: the two tables
    # reference each other, so source_items is created first with a
    # plain nullable UUID column, document_snapshots is created next
    # with its (one-directional) FK to source_items, and only then is
    # the composite ownership FK added via ALTER TABLE (step 3 below).
    # No DEFERRABLE constraint is needed because the runtime write order
    # (section 13) always inserts the item with latest_snapshot_id NULL
    # first.
    op.create_table(
        "source_items",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("dedupe_key", sa.Text(), nullable=False),
        sa.Column("source_id", sa.Text(), nullable=False),
        sa.Column("publisher", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=False),
        sa.Column("published_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("first_fetched_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("latest_snapshot_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("event_id", sa.Text(), nullable=True),
        sa.Column(
            "authors",
            postgresql.ARRAY(sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'"),
        ),
        sa.Column(
            "tags", postgresql.ARRAY(sa.Text()), nullable=False, server_default=sa.text("'{}'")
        ),
        sa.Column("language", sa.Text(), nullable=False, server_default=sa.text("'en'")),
        sa.UniqueConstraint("dedupe_key", name="uq_source_items_dedupe_key"),
    )
    op.create_index(
        _KEYSET_INDEX_NAME,
        "source_items",
        [sa.text("first_fetched_at DESC"), sa.text("id DESC")],
        unique=False,
    )

    # -- 2. document_snapshots, with its FK to source_items ------------
    op.create_table(
        "document_snapshots",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "source_item_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(
                "source_items.id",
                name="fk_document_snapshots_source_item_id_source_items",
                ondelete="RESTRICT",
                onupdate="RESTRICT",
            ),
            nullable=False,
        ),
        sa.Column("fetched_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("content_text", sa.Text(), nullable=False),
        sa.Column("raw_location", sa.Text(), nullable=True),
        sa.Column("etag", sa.Text(), nullable=True),
        sa.Column("last_modified", sa.Text(), nullable=True),
        sa.Column("collector_version", sa.Text(), nullable=True),
        sa.UniqueConstraint(
            "source_item_id", "content_hash", name="uq_document_snapshots_source_item_id"
        ),
        # The target of source_items' composite ownership FK below --
        # the primary key already makes `id` unique, but PostgreSQL
        # requires a matching unique key for a two-column reference.
        sa.UniqueConstraint("id", "source_item_id", name="uq_document_snapshots_id"),
    )

    # -- 3. The composite ownership FK, added via ALTER TABLE -----------
    # Proves at the storage layer that latest_snapshot_id belongs to
    # *this* item, not merely that some snapshot with that id exists
    # (ADR 0002 section 9).
    op.create_foreign_key(
        _LATEST_SNAPSHOT_FK_NAME,
        "source_items",
        "document_snapshots",
        ["latest_snapshot_id", "id"],
        ["id", "source_item_id"],
        ondelete="RESTRICT",
        onupdate="RESTRICT",
    )

    # -- 4. Phase-1 immutability triggers (ADR 0002 section 11) --------
    #
    # source_items -- BEFORE UPDATE, row-level: raise if ANY of the five
    # identity columns changes. `IS DISTINCT FROM` (not `<>`) so NULL vs
    # NULL is "unchanged", matching how an idempotent rewrite of the
    # mutable metadata (which never touches these five columns) must
    # remain permitted.
    identity_checks = "\n".join(
        f"""
    IF OLD.{column} IS DISTINCT FROM NEW.{column} THEN
        RAISE EXCEPTION 'source_items.% is immutable', '{column}';
    END IF;"""
        for column in _PROTECTED_SOURCE_ITEM_COLUMNS
    )
    op.execute(
        f"""
        CREATE FUNCTION {_SOURCE_ITEMS_IDENTITY_FUNCTION}() RETURNS trigger AS $$
        BEGIN{identity_checks}
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        f"""
        CREATE TRIGGER {_SOURCE_ITEMS_IDENTITY_TRIGGER}
        BEFORE UPDATE ON source_items
        FOR EACH ROW
        EXECUTE FUNCTION {_SOURCE_ITEMS_IDENTITY_FUNCTION}();
        """
    )

    # document_snapshots -- whole-row immutable: BEFORE UPDATE and
    # BEFORE DELETE (row-level, always raise) plus BEFORE TRUNCATE
    # (statement-level -- TRUNCATE is a separate statement the row-level
    # DELETE trigger never sees, so it needs its own trigger).
    op.execute(
        f"""
        CREATE FUNCTION {_SNAPSHOTS_BLOCK_UPDATE_FUNCTION}() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION
                'document_snapshots rows are immutable; UPDATE is not permitted (id=%)', OLD.id;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        f"""
        CREATE TRIGGER {_SNAPSHOTS_BLOCK_UPDATE_TRIGGER}
        BEFORE UPDATE ON document_snapshots
        FOR EACH ROW
        EXECUTE FUNCTION {_SNAPSHOTS_BLOCK_UPDATE_FUNCTION}();
        """
    )
    op.execute(
        f"""
        CREATE FUNCTION {_SNAPSHOTS_BLOCK_DELETE_FUNCTION}() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION
                'document_snapshots rows are immutable; DELETE is not permitted (id=%)', OLD.id;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        f"""
        CREATE TRIGGER {_SNAPSHOTS_BLOCK_DELETE_TRIGGER}
        BEFORE DELETE ON document_snapshots
        FOR EACH ROW
        EXECUTE FUNCTION {_SNAPSHOTS_BLOCK_DELETE_FUNCTION}();
        """
    )
    op.execute(
        f"""
        CREATE FUNCTION {_SNAPSHOTS_BLOCK_TRUNCATE_FUNCTION}() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'document_snapshots rows are immutable; TRUNCATE is not permitted';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        f"""
        CREATE TRIGGER {_SNAPSHOTS_BLOCK_TRUNCATE_TRIGGER}
        BEFORE TRUNCATE ON document_snapshots
        FOR EACH STATEMENT
        EXECUTE FUNCTION {_SNAPSHOTS_BLOCK_TRUNCATE_FUNCTION}();
        """
    )


def downgrade() -> None:
    # Reverse order of upgrade(). Drops only the application objects
    # this revision created -- never alembic_version, which Alembic
    # creates and manages itself (section 7, Risks: "The initial
    # revision's downgrade() drops only the application objects it
    # created").
    op.execute(f"DROP TRIGGER {_SNAPSHOTS_BLOCK_TRUNCATE_TRIGGER} ON document_snapshots")
    op.execute(f"DROP FUNCTION {_SNAPSHOTS_BLOCK_TRUNCATE_FUNCTION}()")
    op.execute(f"DROP TRIGGER {_SNAPSHOTS_BLOCK_DELETE_TRIGGER} ON document_snapshots")
    op.execute(f"DROP FUNCTION {_SNAPSHOTS_BLOCK_DELETE_FUNCTION}()")
    op.execute(f"DROP TRIGGER {_SNAPSHOTS_BLOCK_UPDATE_TRIGGER} ON document_snapshots")
    op.execute(f"DROP FUNCTION {_SNAPSHOTS_BLOCK_UPDATE_FUNCTION}()")
    op.execute(f"DROP TRIGGER {_SOURCE_ITEMS_IDENTITY_TRIGGER} ON source_items")
    op.execute(f"DROP FUNCTION {_SOURCE_ITEMS_IDENTITY_FUNCTION}()")

    op.drop_constraint(_LATEST_SNAPSHOT_FK_NAME, "source_items", type_="foreignkey")

    op.drop_table("document_snapshots")

    op.drop_index(_KEYSET_INDEX_NAME, table_name="source_items")
    op.drop_table("source_items")
