"""SQLAlchemy 2.0 ORM models for the ingestion-owned persistence tables
(docs/adr/0002-postgres-pgvector.md sections 8, 9). Mirrors
`shared/schemas.py`'s `SourceItem` and `DocumentSnapshot` Pydantic
contract field-for-field; any divergence between this file and that
contract is a bug, the same rule `shared/schemas.py`'s own module
docstring states for its relationship to `docs/API_CONTRACT.md`.
Registers against the one shared `shared.db.metadata` (ADR 0002 section
12.4) -- never a module-local `MetaData`.

Column shape and constraints only -- the Phase-1 immutability triggers,
the `(first_fetched_at DESC, id DESC)` keyset index, and the composite
`(latest_snapshot_id, id)` foreign key's `ALTER TABLE`-based DDL ordering
are created by the hand-written initial Alembic migration
(`alembic/versions/0001_source_items_and_document_snapshots.py`), not
here (ADR 0002 section 16: "hand-written, not autogenerated -- Alembic
autogenerate does not reliably emit `text[]` columns or trigger DDL").
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import ARRAY, ForeignKey, ForeignKeyConstraint, Text, UniqueConstraint, text
from sqlalchemy.dialects.postgresql import TIMESTAMP, UUID
from sqlalchemy.orm import Mapped, mapped_column

from ai_daily_digest.shared.db.metadata import Base


class SourceItemRow(Base):
    """`source_items` (ADR 0002 section 8).

    Five columns -- `id`, `first_fetched_at`, `dedupe_key`, `source_id`,
    `canonical_url` -- are immutable after insertion. That immutability
    is enforced by application-level repository restriction (layer 2,
    `ingestion/db/repository.py`) and by a storage-level `BEFORE UPDATE`
    trigger (layer 3, the initial migration) -- never by anything in
    this module, which only declares column shape and constraints.
    """

    __tablename__ = "source_items"
    __table_args__ = (
        UniqueConstraint("dedupe_key"),
        # Composite ownership FK (ADR 0002 section 9): proves at the
        # storage layer that `latest_snapshot_id` belongs to *this*
        # item, not merely that some snapshot with that id exists. The
        # two tables reference each other, so `use_alter=True` tells
        # SQLAlchemy (and the hand-written migration, which mirrors this
        # same ordering) to add this constraint via `ALTER TABLE` after
        # both tables exist, rather than needing a `DEFERRABLE`
        # constraint or a table-creation-order deadlock.
        ForeignKeyConstraint(
            ["latest_snapshot_id", "id"],
            ["document_snapshots.id", "document_snapshots.source_item_id"],
            ondelete="RESTRICT",
            onupdate="RESTRICT",
            use_alter=True,
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True)
    dedupe_key: Mapped[str] = mapped_column(Text, nullable=False)
    source_id: Mapped[str] = mapped_column(Text, nullable=False)
    publisher: Mapped[str] = mapped_column(Text, nullable=False)
    title: Mapped[str] = mapped_column(Text, nullable=False)
    canonical_url: Mapped[str] = mapped_column(Text, nullable=False)
    published_at: Mapped[datetime | None] = mapped_column(TIMESTAMP(timezone=True))
    updated_at: Mapped[datetime | None] = mapped_column(TIMESTAMP(timezone=True))
    first_fetched_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), nullable=False)
    # Mutable -- advances only through advance_latest_snapshot_and_metadata's
    # conditional update (ADR 0002 section 12.1); no other write path
    # touches this column.
    latest_snapshot_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True))
    event_id: Mapped[str | None] = mapped_column(Text)
    authors: Mapped[list[str]] = mapped_column(
        ARRAY(Text), nullable=False, server_default=text("'{}'")
    )
    tags: Mapped[list[str]] = mapped_column(
        ARRAY(Text), nullable=False, server_default=text("'{}'")
    )
    language: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'en'"))
    # `PRIMARY KEY (id)` is implied by `primary_key=True` above.
    # `(first_fetched_at DESC, id DESC)` -- the /v1/updates keyset index
    # (ADR 0002 section 8) -- is created directly by the migration
    # (`op.create_index`), not declared here.


class DocumentSnapshotRow(Base):
    """`document_snapshots` (ADR 0002 section 9).

    Whole-row immutable after insertion. Enforced by repository
    restriction (layer 2) and a storage-level `BEFORE UPDATE`/`DELETE`
    row-level trigger plus a `BEFORE TRUNCATE` statement-level trigger
    (layer 3, the initial migration).
    """

    __tablename__ = "document_snapshots"
    __table_args__ = (
        # The snapshot idempotency key: a re-fetch producing identical
        # content must not create a second row.
        UniqueConstraint("source_item_id", "content_hash"),
        # The target of source_items' composite ownership FK above --
        # the primary key already makes `id` unique, but PostgreSQL
        # requires a matching unique key for a two-column reference.
        UniqueConstraint("id", "source_item_id"),
    )

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True)
    source_item_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("source_items.id", ondelete="RESTRICT", onupdate="RESTRICT"),
        nullable=False,
    )
    fetched_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), nullable=False)
    content_hash: Mapped[str] = mapped_column(Text, nullable=False)
    content_text: Mapped[str] = mapped_column(Text, nullable=False)
    raw_location: Mapped[str | None] = mapped_column(Text)
    etag: Mapped[str | None] = mapped_column(Text)
    last_modified: Mapped[str | None] = mapped_column(Text)
    collector_version: Mapped[str | None] = mapped_column(Text)
